### ISSUE TITLE
SDK compilation (mismatch of source files)

### ISSUE THREAD

**Issue by vladnusimovich** [madamic/zynq_tdc#1]
Hi Team

I cloned your repository and successfully compiled your code on the vivado. 
But when I take the source file "TDCServer2.c" to compile in SDK 2018.2, there are mismatches of include files 

../src/tdcm.c:22:10: fatal error: sys/socket.h: No such file or directory
 #include <sys/socket.h>

Where can I take these files:
#include <sys/mman.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>

Best Regards Vladimir

**Comment by madamic** [comment]
Hi Vladimir! 

You should copy the C source file on the actual Red Pitaya Linux system, and compile it there, with the gcc installed on Red Pitaya. These files that you are missing are RP Linux system files, that's why you can't compile the code on your machine. Please see the "Setup on the Red Pitaya system" part of readme for instructions. I never used SDK for this project.

Good luck! And if you have any further issues, please let me know. 

Michel
